export const API_ENDPOINTS = {
  ENVIRONMENT_INFO: '/deploy',
  PROMOTE_DEPLOYMENT: '/promote-deployment',
  DELETE_RELEASE_BINDING: '/delete-release-binding',
  CELL_DIAGRAM: '/cell-diagram',
  RUNTIME_LOGS: '/logs/component',
  DEPLOYEMNT_WORKLOAD: '/workload',
  UPDATE_BINDING: '/update-binding',
  DASHBOARD_BINDINGS_COUNT: '/dashboard/bindings-count',
  CREATE_RELEASE: '/create-release',
  DEPLOY_RELEASE: '/deploy-release',
  COMPONENT_RELEASE_SCHEMA: '/component-release-schema',
  RELEASE_BINDINGS: '/release-bindings',
  PATCH_RELEASE_BINDING: '/patch-release-binding',
  ENVIRONMENT_RELEASE: '/environment-release',
  WORKFLOW_SCHEMA: '/workflow-schema',
  COMPONENT_WORKFLOW_SCHEMA: '/component-workflow-schema',
} as const;
