apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-openchoreo-component
  title: Create OpenChoreo Component
  description: Create a new OpenChoreo component in a specified project and organization.
  tags:
    - openchoreo
spec:
  owner: guests
  type: component
  # Enable user token injection for user-based authorization at OpenChoreo API
  EXPERIMENTAL_formDecorators:
    - id: openchoreo:inject-user-token
  parameters:
    - title: Deployment Source
      required:
        - deploymentSource
      properties:
        deploymentSource:
          title: How would you like to build and deploy?
          type: string
          enum:
            - build-from-source
            - deploy-from-image
            - external-ci
          ui:field: DeploymentSourcePicker

      dependencies:
        deploymentSource:
          allOf:
            # Build from Source: Show repository and build configuration
            - if:
                properties:
                  deploymentSource:
                    const: build-from-source
              then:
                properties:
                  git_source:
                    title: Source Repository
                    type: object
                    ui:field: GitSourceField
                    properties:
                      repo_url:
                        type: string
                      branch:
                        type: string
                      component_path:
                        type: string
                      git_secret_ref:
                        type: string
                  build_template_name:
                    title: Argo Workflows Build Template Name
                    type: string
                    description: Name of the Argo Workflow build template to use
                    ui:field: BuildTemplatePicker
                  build_parameters:
                    title: Build Template Parameters
                    type: object
                    description: Parameters specific to the selected build template
                    ui:field: BuildTemplateParameters
                required:
                  - build_template_name
                  - git_source

            # Deploy from Image: Show container image field
            - if:
                properties:
                  deploymentSource:
                    const: deploy-from-image
              then:
                properties:
                  containerImage:
                    title: Container Image
                    type: string
                    description: The container image to deploy (e.g., docker.io/myorg/myimage:tag)
                required:
                  - containerImage

            # External CI: Show optional CI platform configuration
            - if:
                properties:
                  deploymentSource:
                    const: external-ci
              then:
                properties:
                  external_ci_info:
                    type: 'null'
                    ui:widget: markdown
                    description: |
                      Your component will be created without a workload. Use your CI pipeline (Jenkins, GitHub Actions, GitLab CI) to create workloads via the OpenChoreo API.

                      See the [External CI Integration Guide](https://openchoreo.github.io/docs/integrating-with-openchoreo/external-ci) for setup instructions.
                  ciPlatform:
                    title: CI Platform (Optional)
                    type: string
                    description: Select your CI platform to enable build visibility in Backstage. You can configure this later via the annotation editor.
                    default: none
                    enum:
                      - none
                      - jenkins
                      - github-actions
                      - gitlab-ci
                    enumNames:
                      - Skip - I'll configure this later
                      - Jenkins
                      - GitHub Actions
                      - GitLab CI

            # CI Identifier fields - shown based on ciPlatform selection
            - if:
                properties:
                  ciPlatform:
                    const: jenkins
              then:
                properties:
                  ciIdentifier:
                    title: Jenkins Job Path
                    type: string
                    description: 'Full job path (e.g., /job/my-org/job/my-service or folder/job-name)'
            - if:
                properties:
                  ciPlatform:
                    const: github-actions
              then:
                properties:
                  ciIdentifier:
                    title: GitHub Repository Slug
                    type: string
                    description: 'Repository slug (e.g., my-org/my-repo)'
            - if:
                properties:
                  ciPlatform:
                    const: gitlab-ci
              then:
                properties:
                  ciIdentifier:
                    title: GitLab Project ID
                    type: string
                    description: 'Numeric project ID from GitLab'

    - title: Component Metadata
      required:
        - namespace_name
        - project_name
        - component_name
        - component_type
      properties:
        component_name:
          title: Component Name
          type: string
          description: Name of the component
          ui:field: EntityNamePicker
        displayName:
          title: Display Name
          type: string
          description: Display name of the component
        description:
          title: Description
          type: string
          description: Help others understand what this component is for.
        project_name:
          title: Project Name
          type: string
          description: OpenChoreo project name
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: System
        namespace_name:
          title: Namespace Name
          type: string
          description: Help others understand what this project is for.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Domain
        component_type:
          title: Component Type
          type: string
          description: Describe the type of component you are creating
          enum:
            - Service
            - WebApplication
            - ScheduledTask
            - APIProxy

  steps:
    - id: create-openchoreo-component
      name: Create OpenChoreo Component
      action: openchoreo:component:create
      input:
        namespaceName: ${{ parameters.namespace_name }}
        projectName: ${{ parameters.project_name }}
        componentName: ${{ parameters.component_name }}
        displayName: ${{ parameters.displayName }}
        description: ${{ parameters.description }}
        componentType: ${{ parameters.component_type }}
        deploymentSource: ${{ parameters.deploymentSource }}
        # Build from source parameters
        repoUrl: ${{ parameters.git_source.repo_url }}
        branch: ${{ parameters.git_source.branch }}
        componentPath: ${{ parameters.git_source.component_path }}
        buildTemplateName: ${{ parameters.build_template_name }}
        buildParameters: ${{ parameters.build_parameters }}
        # Deploy from image parameters
        containerImage: ${{ parameters.containerImage }}
        # External CI parameters (for Backstage annotation)
        ciPlatform: ${{ parameters.ciPlatform }}
        ciIdentifier: ${{ parameters.ciIdentifier }}
