apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.project_name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repo_owner }}/${{ values.repo_name }}
    # backstage.io/kubernetes-label-selector: 'core.choreo.dev/organization=default-org,core.choreo.dev/name=${{ values.project_name }}'
    backstage.io/kubernetes-id: ${{ values.project_name }}
  tags:
    - openchoreo
    - project
  labels:
    core.choreo.dev/organization: default-org
    core.choreo.dev/name: ${{ values.project_name }}
  links:
    - url: https://github.com/${{ values.repo_owner }}/${{ values.repo_name }}
      title: GitHub Repo
      icon: github
    - url: https://github.com/openchoreo/openchoreo
      title: OpenChoreo
      icon: web
spec:
  owner: ${{ values.owner }}