apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-openchoreo-trait
  title: Create OpenChoreo Trait
  description: Create a new Trait for your organization.
  tags:
    - openchoreo
    - platform-engineer
spec:
  owner: openchoreo-users
  type: Trait
  # Enable user token injection for user-based authorization at OpenChoreo API
  EXPERIMENTAL_formDecorators:
    - id: openchoreo:inject-user-token
  parameters:
    - title: Trait Metadata
      required:
        - namespace_name
        - trait_name
      properties:
        trait_name:
          title: Trait Name
          type: string
          description: Name of the trait (must be a valid Kubernetes name)
          ui:field: EntityNamePicker
        namespace_name:
          title: Namespace Name
          type: string
          description: Namespace where the trait will be created
          default: domain:default/default
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            defaultKind: Domain
            catalogFilter:
              - kind: Domain
        description:
          title: Description
          type: string
          description: Describe what this Trait is for
    - title: Trait Definition
      required:
        - yaml_definition
      properties:
        yaml_definition:
          title: Trait YAML
          type: string
          description: Edit the Trait YAML definition
          ui:field: TraitYamlEditor
  steps:
    - id: create-openchoreo-trait
      name: Create OpenChoreo Trait
      action: openchoreo:trait:create
      input:
        namespaceName: ${{ parameters.namespace_name }}
        yamlContent: ${{ parameters.yaml_definition }}
