apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-openchoreo-project
  title: Project
  description: Group related components and services within an isolated boundary.
spec:
  owner: openchoreo-users
  type: System (Project)
  # Enable user token injection for user-based authorization at OpenChoreo API
  EXPERIMENTAL_formDecorators:
    - id: openchoreo:inject-user-token
  parameters:
    - title: OpenChoreo Project Details
      required:
        - namespace_name
        - project_name
      properties:
        project_name:
          title: Project Name
          type: string
          description: Name of the project
          ui:field: EntityNamePicker
        displayName:
          title: Display Name
          type: string
          description: Display name of the project
        description:
          title: Description
          type: string
          description: Help others understand what this project is for.
        namespace_name:
          title: Namespace Name
          type: string
          description: Namespace where the project will be created
          default: domain:default/default
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            defaultKind: Domain
            catalogFilter:
              - kind: Domain
        # owner:
        #   title: Owner
        #   type: string
        #   description: Owner of the project
        #   ui:field: EntityPicker
        #   ui:options:
        #     catalogFilter:
        #       - kind: Group
        #         spec.type: team
  steps:
    - id: create-openchoreo-project
      name: Create OpenChoreo Project
      action: openchoreo:project:create
      input:
        namespaceName: ${{ parameters.namespace_name }}
        projectName: ${{ parameters.project_name }}
        displayName: ${{ parameters.displayName }}
        description: ${{ parameters.description }}
  output:
    links:
      - title: View Project
        icon: catalog
        entityRef: ${{ steps['create-openchoreo-project'].output.entityRef }}
