import { createTemplateAction } from '@backstage/plugin-scaffolder-node';
import {
  createOpenChoreoApiClient,
  assertApiResponse,
} from '@openchoreo/openchoreo-client-node';
import { Config } from '@backstage/config';
import { z } from 'zod';
import {
  type ImmediateCatalogService,
  translateResourceToEntity,
} from '@openchoreo/backstage-plugin-catalog-backend-module';

// Kubernetes DNS subdomain name validation
const K8S_NAME_PATTERN =
  /^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$/;
const MAX_NAME_LENGTH = 253;

/**
 * Strip a Backstage entity ref prefix (`domain:default/finance`) down to the
 * bare name. Form inputs from `ProjectNamespaceField` already arrive bare,
 * but legacy callers may still pass the full ref.
 */
function stripEntityRefPrefix(value: string): string {
  const parts = value.split('/');
  return parts[parts.length - 1];
}

/**
 * Scaffolder action that creates an OpenChoreo Resource via the
 * openchoreo-api and immediately inserts the corresponding entity into
 * the Backstage catalog. Takes structured input matching what the per-type
 * templates generated by `RtdToTemplateConverter` emit, then builds the
 * Resource CR body server-side. Mirrors the structured shape used by
 * `openchoreo:component:create`.
 */
export const createResourceAction = (
  config: Config,
  immediateCatalog: ImmediateCatalogService,
) => {
  return createTemplateAction({
    id: 'openchoreo:resource:create',
    description: 'Create OpenChoreo Resource',
    schema: {
      input: (zImpl: typeof z) =>
        zImpl.object({
          namespaceName: zImpl
            .string()
            .describe('Namespace where the Resource will be created'),
          projectName: zImpl
            .string()
            .describe('Project that will own the Resource'),
          resourceName: zImpl
            .string()
            .max(
              MAX_NAME_LENGTH,
              `Resource name must not exceed ${MAX_NAME_LENGTH} characters`,
            )
            .regex(
              K8S_NAME_PATTERN,
              'Resource name must be a valid Kubernetes name: lowercase letters, numbers, hyphens, or dots only. Must start and end with an alphanumeric character.',
            )
            .describe('Unique name for the Resource'),
          displayName: zImpl
            .string()
            .optional()
            .describe('Human-readable display name for the Resource'),
          description: zImpl
            .string()
            .optional()
            .describe('Description of what this Resource is for'),
          typeKind: zImpl
            .enum(['ResourceType', 'ClusterResourceType'])
            .describe(
              'Whether the picked type is namespace-scoped (ResourceType) or cluster-scoped (ClusterResourceType)',
            ),
          typeName: zImpl
            .string()
            .describe(
              'Name of the (Cluster)ResourceType template the Resource consumes',
            ),
          parameters: zImpl
            .record(zImpl.unknown())
            .optional()
            .describe('Parameter values bound to the picked type\'s schema'),
        }),
      output: (zImpl: typeof z) =>
        zImpl.object({
          resourceName: zImpl
            .string()
            .describe('The name of the created Resource'),
          namespaceName: zImpl
            .string()
            .describe('The namespace where the Resource was created'),
          projectName: zImpl
            .string()
            .describe('The project that owns the created Resource'),
          entityRef: zImpl
            .string()
            .describe('Entity reference for the created Resource'),
        }),
    },
    async handler(ctx) {
      ctx.logger.debug(
        `Creating Resource with parameters: ${JSON.stringify(ctx.input)}`,
      );

      const namespaceName = stripEntityRefPrefix(ctx.input.namespaceName);
      const projectName = stripEntityRefPrefix(ctx.input.projectName);
      const {
        resourceName,
        displayName,
        description,
        typeKind,
        typeName,
        parameters,
      } = ctx.input;

      const baseUrl = config.getString('openchoreo.baseUrl');
      const authzEnabled =
        config.getOptionalBoolean('openchoreo.features.auth.enabled') ?? true;
      const token = authzEnabled
        ? ctx.secrets?.OPENCHOREO_USER_TOKEN
        : undefined;

      if (authzEnabled && !token) {
        throw new Error(
          'User authentication token not available. Please ensure you are logged in.',
        );
      }

      const client = createOpenChoreoApiClient({
        baseUrl,
        token,
        logger: ctx.logger,
      });

      // displayName / description are carried as annotations on the Resource
      // CR (consistent with the Component side and with how the catalog
      // translator reads them back).
      const annotations: Record<string, string> = {};
      if (displayName) {
        annotations['openchoreo.dev/display-name'] = displayName;
      }
      if (description) {
        annotations['openchoreo.dev/description'] = description;
      }

      const hasParameters =
        parameters && Object.keys(parameters).length > 0;

      const apiBody: Record<string, unknown> = {
        metadata: {
          name: resourceName,
          ...(Object.keys(annotations).length > 0 && { annotations }),
        },
        spec: {
          type: { kind: typeKind, name: typeName },
          owner: { projectName },
          ...(hasParameters && { parameters }),
        },
      };

      try {
        ctx.logger.info(
          `Sending Resource creation request to namespace '${namespaceName}': ${JSON.stringify(
            apiBody,
          )}`,
        );

        const { data, error, response } = await client.POST(
          '/api/v1/namespaces/{namespaceName}/resources',
          {
            params: {
              path: { namespaceName },
            },
            body: apiBody as any,
          },
        );

        assertApiResponse({ data, error, response }, 'create Resource');

        const resultData = data as Record<string, unknown>;
        const metadata = resultData.metadata as
          | Record<string, unknown>
          | undefined;
        const resultName = (metadata?.name as string) || resourceName;

        ctx.logger.debug(
          `Resource created successfully: ${JSON.stringify(resultData)}`,
        );

        try {
          ctx.logger.info(
            `Inserting Resource '${resultName}' into catalog immediately...`,
          );

          const defaultOwner =
            config.getOptionalString('openchoreo.defaultOwner') ||
            'openchoreo-users';

          const entity = translateResourceToEntity(
            {
              name: resultName,
              uid: metadata?.uid as string | undefined,
              displayName,
              description,
              projectName,
              typeName,
              typeKind,
              parameters: hasParameters ? parameters : undefined,
              createdAt: new Date().toISOString(),
            },
            namespaceName,
            {
              locationKey: 'OpenChoreoEntityProvider',
              defaultOwner: `group:default/${defaultOwner}`,
            },
          );

          await immediateCatalog.insertEntity(entity);

          ctx.logger.info(
            `Resource '${resultName}' successfully added to catalog`,
          );
        } catch (catalogError) {
          ctx.logger.error(
            `Failed to immediately add Resource to catalog: ${catalogError}. ` +
              `Resource will be visible after the next scheduled catalog sync.`,
          );
        }

        ctx.output('resourceName', resultName);
        ctx.output('namespaceName', namespaceName);
        ctx.output('projectName', projectName);
        ctx.output('entityRef', `resource:${namespaceName}/${resultName}`);
      } catch (err) {
        ctx.logger.error(`Error creating Resource: ${err}`);
        throw err instanceof Error
          ? err
          : new Error(`Failed to create Resource: ${err}`);
      }
    },
  });
};
